### ISSUE TITLE
Remove reliance on predefined `Oracle`s

### ISSUE THREAD

**Issue by benthecarman** [p2pderivatives/rust-dlc#174]
Going to try and work on this throughout the next couple of weeks but wanted to document my thoughts here to get feedback.

Currently there are a few problems with the `Oracle` trait.

1. They must be defined upfront, this means that if you want to use a new oracle it normally requires a restart
2. The api is synchronous, so to do this in something like wasm you would need to have a background process polling for results.
3. Requires a standard api for individual oracles. Would be nicer to just to be able to input announcements and attestations manually 
4. Requires to wait for the event to mature to close. Would be nice to close right when I have the signatures.

For closing this is easy to fix, will just need to add a closing function which I was able to do here: https://github.com/benthecarman/rust-dlc/commit/dbc45691c1fedfc9a4227d0960bef47925127d12
However this does not solve everything. As for the side that does not execute the close will not be aware of the closing tx. Would need to add a way to sync transactions and have our DLC state updated.

For opening we need to add a way to pass in the oracle announcements when creating the offer.

**Comment by Tibo-lg** [comment]
Some comments:
1. Yes, that's definitely a limitation. I guess the only way is to use a `Box` or something dynamic (was trying to avoid that as much as possible but I think here there is no other way.
2. `Async` is definitely something that would be nice to have, though I feel it's an "all or nothing" so if the oracle trait was async it would be best to have other traits async as well (maybe the wallet one is an exception).
3. I'm not sure I understand this, you can have whatever API you want on the oracle, it just needs to implement the trait so that `rust-dlc` can query it.
4. That's something I've heard before, but also don't really get. Events define `maturity_time`, which is the earliest time at which the oracle is expected to release the attestation for it. If you expect it to be available anytime, just set it to something early (there might be some check that maturity is in the future, but if that's an issue I find it more meaningful to change this). 

> For closing this is easy to fix, will just need to add a closing function which I was able to do here: https://github.com/benthecarman/rust-dlc/commit/dbc45691c1fedfc9a4227d0960bef47925127d12

> For opening we need to add a way to pass in the oracle announcements when creating the offer.

Would that basically mean getting rid of the `Oracle` trait? I'd need to think about it, kind of like it, but it's also nice to be able to just call `periodic_check` and get things done automatically. Or I wonder if you should maybe just use the static methods from `contract_updater.rs`. I had started to extract these static methods so that people could still use them without having to use the actual `Manager` struct. They might not be sufficient right now but that might be something to consider.

**Comment by Tibo-lg** [comment]
> My thinking was basically making it optional, the periodic check will still do it if it has the oracle, but you can always close manually.

That sounds like a good idea. But (and maybe that's what you were referring to in your first message) I'm not sure how to handle that on the accepting side. For the offering side we can just pass the oracle info together with the event info, but can't think of a good way to do it when receiving an offer. Do you have some idea for that?

**Comment by benthecarman** [comment]
The offer includes the oracle announcement so you don't need it on the accepting side
