### ISSUE TITLE
Integration tests freeze 

### ISSUE THREAD

**Issue by sosaucily** [p2pderivatives/rust-dlc#68]
The integration tests often freeze up, this happens when running a single integration test, or all of them. stopping and starting the bitcoin node in docker always seems to get the tests to run, but I have noticed that I sometimes need to restart it for each test to run. So that means 4 restarts for the 4 integration tests. 

Any ideas?

**Comment by Tibo-lg** [comment]
> So that means 4 restarts for the 4 integration tests.

This is how the integration tests are designed to run at the moment. The reason is that having a clear state ensures that you don't have undesired interactions between the tests. I've actually added a script to run all integration test [here](https://github.com/p2pderivatives/rust-dlc/pull/57/files#diff-5c5222c614eaf955d95c510c6a373a76bd2bd9a761cde1239993298657bd1b60), but it's not on master yet.
If you want to be able to run integration tests without restarting the bitcoin image you'd have to update [this](https://github.com/p2pderivatives/rust-dlc/blob/master/bitcoin-test-utils/src/rpc_helpers.rs#L24) so that it loads the wallet if it already exists, as long as it doesn't break anything I'd be fine with it.

**Comment by Tibo-lg** [comment]
It is now possible to run multiple integration tests in a row without restarting the environment (it's not possible to run them concurrently though and probably won't be, because the tests rely on generating blocks and waiting for electrs to have caught up which becomes messy if multiple tests do it at the same time).
